tls_server_config:
  cert_file: /etc/node_exporter/node_exporter.crt
  key_file: /etc/node_exporter/node_exporter.key
basic_auth_users:
  prometheus: $2y$12$ES896ZFqiEWkPaT1kFhuE.vTT3NBXCyw9PUgkc27ZtkalgS7jtEiO
